// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjztohozsxuedwntnmjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqenRvaG96c3h1ZWR3bnRubWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MTUzMzIsImV4cCI6MjA3MTQ5MTMzMn0.NWXQzravnsJRKuF_sicGVi0BvMgQe-WvYamjO1EgZMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});